[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "adithya-domain-specific-bpe-tokenizer"
version = "0.1.0"
description = "A domain-specific Byte Pair Encoding tokenizer for medical and general NLP corpora"
readme = "README.md"
requires-python = ">=3.9"
license = "MIT"

authors = [
    { name = "Adithya Prabhu" }
]

keywords = [
    "tokenizer",
    "bpe",
    "nlp",
    "llm",
    "medical-nlp",
    "byte-pair-encoding"
]

classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Operating System :: OS Independent",
]

dependencies = []

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
include = ["domain_specific_bpe_tokenizer*"]